//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Our_decor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsWithCost
    {
        public int Id { get; set; }
        public string Article { get; set; }
        public string ProductType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal MinPartnerCost { get; set; }
        public decimal RollWidth { get; set; }
        public decimal MaterialCost { get; set; }
        public Nullable<int> ProductionTime { get; set; }
        public Nullable<int> WorkshopNumber { get; set; }
        public Nullable<int> WorkersCount { get; set; }
    }
}
