//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Our_decor
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterialsView
    {
        public int ProductId { get; set; }
        public string Article { get; set; }
        public string ProductName { get; set; }
        public string MaterialName { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public decimal Cost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
